# 只需要写 root
jdbc.user=root
# 确保密码正确
jdbc.password=20031207LLb
url=jdbc:mysql://localhost:3306/carRental?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
jdbc.driverClass=com.mysql.cj.jdbc.Driver